### ISSUE TITLE
add san fran bay area

### ISSUE THREAD

**Issue by mpadge** [ropensci/bikedata#34]
copy of [main data issue](https://github.com/mpadge/bikedata/issues/2) - [data are here](http://www.bayareabikeshare.com/open-data). Unfortunately not a NABSA system, so this'll take a bit more work than Philadelphia.

**Comment by tombuckley** [comment]
@mpadge sounds like the upcoming Ford GoBike launch will be NABSA standardized, if thats helpful to know.

**Comment by tombuckley** [comment]
@mpadge the launch for that is June, not sure about data releases

**Comment by tombuckley** [comment]
kara oberg wanted to make sure i let you know about the newish feed for sf here: https://www.fordgobike.com/system-data

**Comment by mpadge** [comment]
yeah thanks tom, that's the main link above. I've just gotta find time to incorporate these data, which is a bit of work because the format is quite different from all other systems. I didn't realise "Bay Area Bike Share" had been bought out by Ford - interesting developments!

**Comment by mpadge** [comment]
Oh, but i see that you said above that it should be NABSA standardized - I'll have a look asap

**Comment by tombuckley** [comment]
@mpadge yeah, i think the update is that its NABSA now? thanks for taking a look. sorry i didn't clarify that.

**Comment by tombuckley** [comment]
@mpadge and yes with the expansion this summer the whole system is 10x larger i think.

**Comment by mpadge** [comment]
These data have still not been released. Note that the [Ford GoBike Data License Agreement](https://assets.fordgobike.com/data-license-agreement.html) states that one may **not**:

    (c) Access the Data by means other than the interface Motivate provides or authorizes for that purpose; ...
    (e) Use data mining or other extraction methods in connection with Motivate's website, mobile application or the Data

But if they do eventually provide the data on an AWS service (or similar), then downloading will be using "the interface Motivate provides". Point (e) is more ambiguous, and could potentially prohibit any means of extracting the data. Not much could be done in that case, but an outright prohibition on extracting data would entirely contradict the whole point of publishing them, so that seems unlikely. Whatever, we still just have to wait and see whether the data actually appear

**Comment by tibbl35** [comment]
bummer, thanks @mpadge. i'll ask about this.

**Comment by tibbl35** [comment]
@mpadge sounds like the data should be available "any day now." sorry i couldn't be more helpful. i can drop a note in this issue when they are released.

**Comment by tibbl35** [comment]
@mpadge sf bay area data should be available here now:

https://www.fordgobike.com/system-data

**Comment by mpadge** [comment]
wow, is that just a coincidence, or did you work some magic there @tibbl35? Either way, that is fabulous news. Now the important Q: Are you interested in helping get them in? It's not too much work, and is all documented in [the wiki](https://github.com/ropensci/bikedata/wiki/How-to-add-a-new-city). Let me know if so, and we can work out a suitable division of labour. Even if not: Thanks!

**Comment by tibbl35** [comment]
@mpadge i just asked to hear about the release. kara worked the magic. 

nice docs! i want to try this out. i can get it done over the next week or so in off hours if that timeline is ok.

**Comment by mpadge** [comment]
even slower here, so there's absolutely no rush at all, but it'd be great if you wanted to contribute - you will of course get full acknowledgement!

**Comment by mpadge** [comment]
Now done via commits leading up to [this one](https://github.com/ropensci/bikedata/commit/fce7fcd57f08d79f68b6847ce523107a6e34966e).
