### ISSUE TITLE
Can't use store_bikedata without specifying a city

### ISSUE THREAD

**Issue by MathieuMarauri** [ropensci/bikedata#48]
Hello, 

I am trying out your package and I wanted to download and store the data for every cities in a database outside the temporary directory to be able to play the data without having the redownloading it each time. 

I use the following code 

```r
bike_dt <- file.path('data/database', 'bikedata.sqlite')
store_bikedata(bikedb = bike_dt)
# enter 'yes' in the console 
```

But this fails with the error `Error in store_bikedata(bikedb = bike_dt) : 
  argument "city" is missing, with no default`. If I take this line out of the function source code and retry I have this error: `Error in store_bikedata(bikedb = bike_dt) : 
  argument "city" is missing, with no default`.

This package ooks nice and I am looking forward looking into the data. 

Thanks for your help,

Mathieu

**Comment by mpadge** [comment]
thanks @MathieuMarauri. I had disabled that option because I thought it was potentially dangerous if people just typed one line and inadvertently started a 50-100GB download. I then put the text warning and question prompt in, but forgot to re-enable actually doing it. Should now work.

**Comment by MathieuMarauri** [comment]
Thank you very much for the quick answer.

Have a good day.
