### ISSUE TITLE
Trouble downloading London files for March to May 2017

### ISSUE THREAD

**Issue by philstraforelli** [ropensci/bikedata#53]
I had no problem getting the data for London in the rest of 2017 (except after December 5, I'm assuming those are not available yet?) - but these files seem to not download correctly. 

```
dl_bikedata("lo", paste0(getwd(),"/bikedata"), dates = 201703:201705)
#> Downloading 50 Journey Data Extract 22Mar2017-28Mar2017.csv
#> Downloading 51 Journey Data Extract 29Mar2017-04Apr2017.csv
#> Downloading 52 Journey Data Extract 05Apr2017-11Apr2017.csv
#> Downloading 55JourneyData Extract26Apr2017-02May2017.csv
#> Downloading 56JourneyDataExtract 03May2017-09May2017.csv
```

I'm getting the message that they downloaded, but those specific files do not appear in the directory. They stand out from the other files in that they have spaces - which is potentially what's causing the issue. Is there another way to acquire them?

**Comment by mpadge** [comment]
yeah, you're right, and it is likely something to do with the space. I'll check it out and get back to you. Thanks!

**Comment by mpadge** [comment]
@philstraforelli That commit converts spaces in the URLs to "%20", and now all works. Thanks for finding that problem! :smile:

**Comment by philstraforelli** [comment]
Thanks @mpadge ! I'm still having one file missing: I'm not getting file `49JourneyDataExtract15Mar2017-21Mar2017.csv` when I run the following line: `dl_bikedata("lo", paste0(getwd(),"/bikedata"), dates = 201703)`. Can you confirm whether the file is available?

**Comment by mpadge** [comment]
ah, that's a `.xlsx` file; see the list [here](http://cycling.data.tfl.gov.uk/). I'll have to add the `readxl` package to parse that one.
