### ISSUE TITLE
Checkout gbfs

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/bikedata#76]
Just saw this and thought worth asking: worth using? In case it helps add more cities: https://github.com/ds-civic-data/gbfs

**Comment by tibbl35** [comment]
@Robinlovelace it would be cool to set up something to log responses from gbfs's, given how many systems have implemented it. could then use bikedata historical trips to help model origins and destinations, given that gbfs doesn't return that?

**Comment by mpadge** [comment]
Yeah, the `gbfs` is just live feeds of station status, but I suppose that could potentially be incorporated down the track. It would be a huge expansion, and other packages already exist for that, but I suppose in the spirit of empire-building and all it ought to be considered ...

**Comment by mpadge** [comment]
I'm gunna close this for the moment as out of scope. Current thinking is that `bikedata` should restrict itself to being a repo exclusively for historical trip data, and that `gbfs` feeds really are a categorically different thing.
