### ISSUE TITLE
potentially inverted lat/lng in sf bay area stations

### ISSUE THREAD

**Issue by tbuckl** [ropensci/bikedata#80]
i would need to verify which commit i was running at but i had to do this for sf bay area stations:

https://github.com/BayAreaMetro/Data-And-Visualization-Projects/blob/master/bikeshare/bikeshare_od_maps.R#L25-L28

**Comment by mpadge** [comment]
Sure, that'd be cool too. How about you do that and I'll check out mapping your SF movements onto the street network

**Comment by tbuckl** [comment]
looks like this is on the current master (https://github.com/ropensci/bikedata/tree/8ad31ae328d3b8d8990394f25501e099d8698f35). 

here's a mock for a fix:

https://github.com/ropensci/bikedata/tree/8ad31ae328d3b8d8990394f25501e099d8698f35

i dug back down into the read stations functions a bit and can't seem to find evidence that 'sf' has its own functions, which makes this more mysterious. 

normally, i'd debug this by setting breakpoints. not sure how to do that with the C

**Comment by tbuckl** [comment]
i set some breakpoints and walked through step by step to find that this is where the read error is happening: https://github.com/ropensci/bikedata/blob/master/R/store-bikedata.R#L183-L189

you probably already knew that @mpadge.

**Comment by tbuckl** [comment]
i probably did at some point too :)

**Comment by tbuckl** [comment]
oh ok so this is a problem for ny too. found it i think.

**Comment by tbuckl** [comment]
will submit a PR with a mock for a check/test for this in a bit

**Comment by mpadge** [comment]
I think that was my bad all along, and should now be fixed with that commit.
