### ISSUE TITLE
London dates not parsed correctly in bike_daily_trips()

### ISSUE THREAD

**Issue by philstraforelli** [ropensci/bikedata#85]
It seems that London files in the csv or Excel sheets are dated Day / Month / Year, instead of Month / Day / Year as it's seen in other cities. It seems that `bike_daily_trips()` expects the dates to be the latter, resulting in erroneous dates parsing, as well as a huge amount of `NA`s. I haven't checked other functions, but I expect the issue to be present throughout.

In case it helps, I've run the following after downloading the files I needed to bring in the CSV files, change their date format, and save back to disk:

```
library(tidyverse)
files_lo <- list.files(path = file.path(getwd(), "bikedata/London"), pattern = ".csv")

all_lo_data <- files_lo %>% 
	map(function(x) {
		read_csv(paste0(file.path(getwd(), "bikedata/London"), "/", x)) %>% 
			mutate_at(vars(c(`Start Date`, `End Date`)), funs(lubridate::dmy_hm(.) %>%
										format("%m/%d/%Y %H:%M:%S")))
	})

walk2(all_lo_data, files_lo, ~ write_csv(.x, path = paste0(file.path(getwd(), "bikedata/London"), "/", .y)))
```

**Comment by mpadge** [comment]
Thanks for that - the whole package recently got restructured to do more intelligent auto-parsing of dates, but I'm now reliant on people directly finding these kinds of inconsistencies. It should be relatively straightforward to fix, so I'll get on to it asap.

**Comment by mpadge** [comment]
Actually seems okay. Can you make sure you have the latest version:
```
packageVersion("bikedata")
# [1] ‘0.2.0.100’
```
All dates for all systems should be DD/MM/YY or DD/MM/YYYY, or else other idosyncratic forms, but there are no systems which use MM/DD/YY(YY). Feel free to re-open is error recurs, but if so, could you please indicate which date ranges cause the errors (because London has thousands of files by now).

**Comment by mpadge** [comment]
oh sorry, just noticed you got the error from `bike_daily_trips()`, which I can indeed reproduce.
